export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const FETCH_SPECIFIC_USERS_START = 'FETCH_SPECIFIC_USERS_START';
export const FETCH_SPECIFIC_USERS_SUCCESS = 'FETCH_SPECIFIC_USERS_SUCCESS';
export const FETCH_SPECIFIC_USERS_FAIL = 'FETCH_SPECIFIC_USERS_FAIL';
